language: node_js

sudo: required

services:
  - docker

script:
  - docker build -t chnaydar/node2 .
  - docker images chnaydar/node2

before_deploy:
  - docker login -u chnaydar -p installe

deploy:
  provider: script
  script: docker push chnaydar/node2
  on:
    branch: main